### ISSUE TITLE
Using `references` when creating a table in a named schema results in error

### ISSUE THREAD

**Issue by DataTables** [tgriesser/knex#1614]
Database: postgres 9.5.3
Knex version: 0.11.9

I'm finding that I'm running into errors when trying to create a table in a postgres schema, that references another table also in that same schema.

I have (using a little Babel async / await magic):

```js
			await db
				.schema
				.withSchema( 'mySchema' )
				.createTable( 'application', table => {
					table.increments( 'id' );
					// ...
				} );

			await db
				.schema
				.withSchema( 'mySchema' )
				.createTable( 'user', table => {
					table.uuid( 'id' )
						.primary()
						.defaultTo( db.raw('uuid_generate_v4()') );
					//...
				} );

			await db
				.schema
				.withSchema( 'mySchema' )
				.createTable( 'user_application', table => {
					table.uuid( 'userId' ).references( 'user.id' );
					table.integer( 'applicationId' ).references( 'application.id' );

					table.unique( [ 'userId', 'applicationId' ] );
				} );
```

which results in: the following error:

> alter table "mySchema"."user_application" add constraint user_application_userid_foreign foreign key ("userId") references "user" ("id") - relation "user" does not exist

Doing a `toString` gives:

```
create table "mySchema"."user_application" ("userId" uuid, "applicationId" integer);
alter table "mySchema"."user_application" add constraint "user_application_userid_foreign" foreign key ("userId") references "user" ("id");
alter table "mySchema"."user_application" add constraint "user_application_applicationid_foreign" foreign key ("applicationId") references "application" ("id");
alter table "mySchema"."user_application" add constraint "user_application_userid_applicationid_unique" unique ("userId", "applicationId")
```

If I execute the query directly in postgres I need to add the schema name to the `references` column name which works.

I did try to use this as a work around:

```
table.uuid( 'userId' ).references( 'mySchema.user.id' );
```

But the SQL it generated basically uses only the first two object elements:

```
alter table "mySchema"."user_application" add constraint "user_application_userid_foreign" foreign key ("userId") references "mySchema" ("user");
```

So I guess you could view the bug in one of two ways (possibly both!):

* When using `references()` it needs to add the schema name.
* If a schema name is given to `references()` it needs to not be truncated.

**Comment by DataTables** [comment]
I've just found a workaround using `inTable`:

```js
table.uuid( 'userId' ).references( 'id' ).inTable( 'mySchema.user' );
```

**Comment by JonathanCMitchell** [comment]
Your integer and references declaration need to be on two different lines. 
Simply define the integer first, then create a reference to another table in another statement.
```
table.integer("user_id").unsigned();
table.foreign("user_id").references("TableName.attr");
```

**Comment by Phibedy** [comment]
Any updates or is the workaround the way to go?

**Comment by maxbol** [comment]
+1, any movement on this? @JonathanCMitchell 's solution does nothing for me, and explicitly referencing the schema in inTable is not an alternative.

**Comment by kjkent** [comment]
+1, this might benefit from some documentation in the meantime -- using @DataTables workaround works for PostgreSQL

**Comment by nharsch** [comment]
It looks like this issue has been resolved?

**Comment by EduardJoy** [comment]
Has there been any progress on this issue? I seems that his is still affecting us in the latest version of knex

**Comment by mercmobily** [comment]
Thank you for reporting this issue about foreign key references not respecting the `withSchema` setting. This is indeed a bug that affects PostgreSQL users (and potentially other databases) when working with schemas.

This issue is still present in the current version of Knex. When you use `withSchema('mySchema')` and create foreign key references, the generated SQL doesn't include the schema prefix for the referenced table, causing PostgreSQL to look for the table in the default (public) schema instead of the specified schema.

I've confirmed the bug with the following test case which demonstrates the problem clearly. When creating tables in a named schema with foreign key relationships, the SQL generated is incorrect:

```javascript
// Expected SQL for foreign key:
// foreign key ("userId") references "mySchema"."user" ("id")

// Actual SQL generated:
// foreign key ("userId") references "user" ("id")
```

The root cause is in `lib/schema/tablecompiler.js:103` where the `foreign` method wraps the `inTable` value but doesn't inherit the schema context from the table builder. The schema information set via `withSchema` isn't propagated to the foreign key constraint generation.

There are currently two open pull requests attempting to fix this issue. PR #5651 takes the approach of making `table.foreign()` automatically use the schema from `withSchema()` when no explicit schema is specified. PR #6169 addresses a related issue about properly handling schema names in foreign key references when they contain dots.

The workaround you discovered using `inTable('mySchema.user')` is currently the best solution whilst we await a proper fix. This explicitly specifies the full schema-qualified table name:

```javascript
table.uuid('userId').references('id').inTable('mySchema.user');
```

However, there's an important caveat with this workaround. As you noted, if you try to include the schema in the references parameter itself like `references('mySchema.user.id')`, Knex incorrectly parses this and treats "mySchema" as the table name and "user" as the column name, resulting in invalid SQL.

From a design perspective, the expected behaviour should be that when using `withSchema()`, all table references within that context should default to the specified schema unless explicitly overridden. This would align with how other database operations work in Knex and match user expectations.

WE are aware of this issue, and it affects multiple users as evidenced by the related issues and ongoing pull requests. The fix would involve modifying the foreign key generation logic to check if a schema context exists and prepend it to the table reference when no explicit schema is provided.

Related Issues:
- #4910 - .foreign & .withSchema?
- #3115 - Migration failing with error relation does not exist
- PR #5651 - Fix .foreign to utilize withSchema setting
- PR #6169 - Fix for foreign key's referencing table schemas

**Comment by mercmobily** [comment]
I think it's important to look at both existing PRs and understand their scope.

**PR #5651 - Schema Context Inheritance Approach**

This PR takes a straightforward approach by storing the schema from `withSchema()` in the foreign key data structure and automatically prepending it when generating SQL. The implementation adds the schema to `foreignData` in `/lib/schema/tablebuilder.js:83-86` and then conditionally prepends it in `/lib/schema/tablecompiler.js:103-107`.

The strength of this approach is its simplicity and alignment with user expectations. When you've specified `withSchema('mySchema')`, it's reasonable to expect that all table references within that context default to that schema. This mirrors how other database operations work in Knex.

However, this approach has a critical limitation: it doesn't properly handle cross-schema foreign keys. If you need to reference a table in a different schema (a common requirement in enterprise applications), the current implementation would incorrectly prepend the context schema even when you've explicitly specified a different one.

**PR #6169 - Parser Enhancement Approach**

This PR takes a different angle by fixing the parsing logic for multi-part table names. The key change in `/lib/schema/tablebuilder.js:112-113` replaces the naive array indexing with `pieces.pop()` for the column name and `pieces.join('.')` for the table name. This elegantly handles both `schema.table` and simple `table` references.

The strength here is proper support for cross-schema foreign keys. You can reference `application.people` from within a `sales` schema context, which is essential for properly normalised database designs. The Microsoft WideWorldImporters example cited by the PR author demonstrates real-world use cases where this is necessary.

The weakness is that it doesn't automatically inherit the schema context from `withSchema()`. Users must explicitly specify the schema every time, even when referencing tables within the same schema, leading to repetitive code.

**The Verdict**

PR #6169's approach is fundamentally more correct because it fixes the broken parsing logic that affects all foreign key references, not just those using `withSchema()`. The current code's assumption that a dotted reference always has exactly two parts is demonstrably wrong and causes failures even without schema contexts.

However, neither PR provides a complete solution. The ideal implementation would:

1. Apply PR #6169's parsing fix to correctly handle multi-part table names
2. Then check if a schema was explicitly provided in the reference
3. If no schema was provided, inherit from `withSchema()` context if available
4. This would provide both automatic schema inheritance AND proper cross-schema support

The combined approach would look something like this in the foreign key reference handling:

```javascript
// After applying the parsing fix from PR #6169
if (!foreignData.inTable.includes('.') && this._schemaName) {
  foreignData.inTable = `${this._schemaName}.${foreignData.inTable}`;
}
```

This would give users the best of both worlds: convenient same-schema references that respect the `withSchema()` context, whilst still allowing explicit cross-schema references when needed.

**Resolution Status**

* PR #5651 has been closed 
* PR #6169has been asked to incorporate the automatic schema inheritance feature from #5651 into their solution. This pragmatic approach consolidates both fixes under a single, actively maintained PR.

The final implementation in PR #6169 will (hopefully!) provide:

1. The parsing fix for multi-part table names (original PR #6169 contribution)
2. Automatic schema inheritance from `withSchema()` context (idea from PR #5651)
3. Proper handling of both same-schema and cross-schema foreign key references

This combined solution will fully resolve the issue whilst maintaining backward compatibility and supporting all use cases.
