### ISSUE TITLE
Reconnecting after database server disconnect/reconnect

### ISSUE THREAD

**Issue by ty10r** [tgriesser/knex#1833]
I searched through the issues to find if others are having trouble attempting to reconnect.

It's been a very long time since these two:
https://github.com/tgriesser/knex/issues/1341
https://github.com/tgriesser/knex/issues/936

Most of the suggestions I have seen in the issues so far are relying on `pool2` and include configuration for `requestTimeout`.

I am on version `0.12.2` of knex, which no longer uses `pool2`. I also can no longer see implementation of `ping` in `src/client.js`.

I'm running tests where I use docker to run these steps:

1) Spin up postgres db in container.
2) Start knex/connect to postgres.
3) Run a test query, evaluate success.
4) Stop postgres db in container.
5) Run test query again, evaluate failure (with config: `{pool: {acquireTimeoutMillis: XXXX}, acquireConnectionTimeout: XXXX)
6) Restart postgres db in container.
7) Run test query again, evaluate success.

Step 7 is failing in the same way step 5 does.

I assumed knex would automatically attempt to reconnect. Is there a way I can cause a reconnection?

If you'd like, I can post this question instead at one of the past conversations on reconnection. I thought it was worth having a new conversation since most of the other conversations include only answers from before switching to `generic-pool`.

**Comment by halt-hammerzeit** [comment]
+1 to implementing autoreconnect feature: it's really inconvenient not having it out-of-the-box.
I didn't even imagine that in such a popular library such a basic issue exists, I assumed it handles everything by itself.

**Comment by ty10r** [comment]
I'm personally not convinced there isn't a way.

There are tests on one of my services that suggest that `0.9.X` was automatically reconnecting.

I am asking this question for these reasons:
1) My test logic/timing may be flawed, if a contributor here told me that it should be reconnecting and how, it should give everyone a better understanding of an undocumented behavior.

2) There may be a work around that the implementors intended when switching pooling (resulting in losing the previous work arounds)

3) If there are absolutely no solutions, then yes, we can wonder about why reconnection does not exist and then find a good solution for its existence.

**Comment by halt-hammerzeit** [comment]
@ty10r Well, given there's absolutely zero results when searching for `reconnect` in this repo, I can state that the absence of a built-in reconnection in this library is a proven fact.
https://github.com/tgriesser/knex/search?utf8=%E2%9C%93&q=reconnect

**Comment by elhigu** [comment]
Lets try to keep future discussion of knex reconnecting to database here. Now that we are using generic-pool it is fair to look again how this works. Would be great if knex would be able to connect again to DB if server was closed and restarted (or network was broken for a while or anything like that).

Would be awesome if we would be able to add some automatic testing for this. Any ideas how to do them would be valuable (or do we just have to stop / restart db servers in CI? for that separate test script that is ran after all others could be viable solution).

**Comment by smulesoft** [comment]
Hi @elhigu, I leave you some comments:

### Reconnection

According to my tests, reconnection is _almost_ working. I've only found one weird scenario (see [this issue](https://github.com/tgriesser/knex/issues/1986)).
The problem is this one: Suppose you restart your database service, and after the restart there is still 1 connection to the old database in the pool. Two things could happen:
- The idle connection is purged because it has stayed idle for `idleTimeoutMillis` (it is evicted). Then, a new connection is created (to the 'new' database), and it can perform queries correclty.
- A client performs a query so the idle connection is used (instead of being evicted). If the `testOnBorrow` flag is set, a call to either `config.poool.validate` or `config.pool.validateAsync` is made. If the function returns `true`, the idle connection is accepted so it will be used. And this is the weird scenario. An invalid connection is being used (it is incorrect because it was created for the old database). In my test, when this happens, the query will just hang indefinitely.

If what I say is correct, maybe you can save this case by correcting the implementation of `config.pool.validate`. Actually, I would implement `validateAsync` instead of `validate` in [client.js](https://github.com/tgriesser/knex/blob/master/src/client.js). And there I would simply do a query like `SELECT 1 as one` (in addition to the check on `connection.__knex__disposed`).


### Testing

In my tests I am using [dockerode](https://github.com/apocas/dockerode) to start and stop postgres containers directly from `node.js` tests, and I am able to reproduce this bug.

Let me know what you think and maybe I'll make myself some time to help you with a PR.

**Comment by elhigu** [comment]
@smulesoft if you are able to add PR which actually can test this somehow on our CI it would be very valuable. 

Problem is that if there is no tests it will break again in the future. I don't have currently resources to write PRs for this stuff by myself.

**Comment by damirm** [comment]
Have the same issue. `validate` function still returns true even If connection with database is closed.
I found fix: set `__knex__disposed` on connection close event. (https://github.com/tgriesser/knex/blob/master/src/dialects/postgres/index.js#L111)
Like this:

```
connection.on('error', (err) => {
  connection.__knex__disposed = err
})
connection.on('end', (err) => {
  connection.__knex__disposed = err
})
```

Tested in postgres dialect.
What cons of that solution?

**Comment by damirm** [comment]
Another solution is check for `connection.connection.stream.readable` in `validate` function. This will be protect from using closed stream. I think that is better than my previous comment.
In this case `validate` function looks like this:
```
  validate: (connection) => {
    if (connection.__knex__disposed) {
      helpers.warn(`Connection Error: ${connection.__knex__disposed}`)
      return false
    }
    if (!connection.connection.stream.readable) {
      return false;
    }
    return this.validateConnection(connection)
  }
```

**Comment by smulesoft** [comment]
Alright, I have a fix inspired on @damirm's first comment -including a reproducing test case which depends on having `docker` insatlled in the machine running tests.
Can I be granted permissions to push a branch on this repo and begin a PR?

**Comment by leebenson** [comment]
As someone that is seeing this thread for the first time after running into rejected connection promises, could someone please do me a quick favour and summarise the status of the fix?

I'm seeing this in my error logs:

> js/release/async.js:17:14) fatal: true }
ERRORS -> { Error: Can't add new command when connection is in closed state
    at Connection._addCommandClosedState (/app/node_modules/mysql2/lib/connection.js:158:13)
    at Connection.query (/app/node_modules/mysql2/lib/connection.js:621:15)
    at /app/node_modules/knex/lib/dialects/mysql/index.js:156:18
    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL2._query (/app/node_modules/knex/lib/dialects/mysql/index.js:150:12)
    at Client_MySQL2.query (/app/node_modules/knex/lib/client.js:211:17)
    at Runner.<anonymous> (/app/node_modules/knex/lib/runner.js:149:36)
    at Runner.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/app/node_modules/bluebird/js/release/method.js:15:34)
    at /app/node_modules/knex/lib/runner.js:61:21
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at /app/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)

I assumed that specifying a `pool` option would add automatic handling of reconnections, but so far the server doesn't seem to have recovered.

Is there some extra configuration that is needed, or something else I'm missing?

Thanks in advance.

**Comment by elhigu** [comment]
@leebenson I believe there is new bug in 0.14 which is causing that error. Maybe related to this https://github.com/tgriesser/knex/issues/2320 and here is other issue about your problem https://github.com/tgriesser/knex/issues/2321

**Comment by vjpr** [comment]
I saw infinite loop of trying to reconnect in 0.14, but it is now fixed in 0.14.2 just as an FYI.

**Comment by shivamtandon** [comment]
Is there a version of mock-knexwhich supports the latest version of knex 0.14.2 as on their page it says it supports maximum upto 0.11 of knex.

Please help?

**Comment by elhigu** [comment]
@shivamtandon your comment has nothing to do with this issue and the question is not really about knex, but `mock-knex` package. Please ask from their developers or stackoverflow. 

I'll delete these comments at some point in future since these does not have anything to do with this thread.

**Comment by analytik** [comment]
This isn't resolved for me in 0.14.2. When I kill a database *in between* making knex queries, everything works. When I make queries, then scale the database to zero replicas, attempt to make more queries, I get the following error - and I get the same error even when I scale the database back up and it's accepting connections and everything.

```
Unhandled rejection TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /project/node_modules/knex/lib/client.js:351:13
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Client_PG.acquireConnection (/project/node_modules/knex/lib/client.js:350:13)
    at Runner.ensureConnection (/project/node_modules/knex/lib/runner.js:215:24)
    at Runner.run (/project/node_modules/knex/lib/runner.js:47:42)
    at Raw.Target.then (/project/node_modules/knex/lib/interface.js:35:43)
    at serveSomeDataFromDatabase (/project/controllers/api.js:12:34)
<Express stuff>
    at /project/app.js:40:17
<more Express stuff>
```

So, steps to reproduce:
* make an knex query and succeed
* bring down database
* make more queries while database is down, receive the above-mentioned error
* bring database up
* never recover and when running knex queries, receive the same error always, forever

I had `{debug: true}` and I got these ONLY the first time the error appeared, just before the above error/stack trace was thrown:

```
Knex:warning - Connection Error: Connection ended unexpectedly
Knex:warning - Connection Error: Connection ended unexpectedly
```

**Comment by elhigu** [comment]
@analytik thanks for I'll look into the report and try to reproduce it by shutting down postgres and your instructions.

**Comment by elhigu** [comment]
@analytik Sorry, I couldn't reproduce your problems with knex 0.14.2. 

```
knex = require('knex')({
        dialect: 'pg',
         debug: true,
        acquireConnectionTimeout: 4 * 1000,
       pool: {
            min: 2,
             max: 2,
            idleTimeoutMillis: 5 * 1000,
            acquireTimeoutMillis: 3 * 1000,
             evictionRunIntervalMillis: 5 * 1000
         },
         connection: 'postgres:///knex_test'
});

> knex('accounts').then(() => console.log('query success')).catch(err => console.log('fale', err))
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> { method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '8288b11f-9b61-4d94-ae71-4e426d0c5d2e',
  toNative: [Function: toNative],
  sql: 'select * from "accounts"' }
query success
> knex.transaction(trx => trx('accounts')).then(() => console.log('query success')).catch(err => console.log('fale', err))
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> { method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '296ba797-eb63-4a05-99b5-8e8c936ea904',
  toNative: [Function: toNative],
  sql: 'select * from "accounts"' }
query success
> // closed postgres app
undefined
> knex('accounts').then(() => console.log('query success')).catch(err => console.log('fale', err))
Knex:warning - Connection Error: Error: connect ECONNREFUSED 127.0.0.1:5432
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> Knex:warning - Connection Error: Error: connect ECONNREFUSED 127.0.0.1:5432
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '81b49338-0571-4870-b322-8d1c73739d61',
  toNative: [Function: toNative],
  sql: 'select * from "accounts"' }
fale { Error: select * from "accounts" - connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
> knex.transaction(trx => trx('accounts')).then(() => console.log('query success')).catch(err => console.log('fale', err))
Knex:warning - Connection Error: Error: select * from "accounts" - connect ECONNREFUSED 127.0.0.1:5432
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> Knex:warning - Connection Error: Error: connect ECONNREFUSED 127.0.0.1:5432
fale { Error: BEGIN; - connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'cf2814bb-e336-460b-9fee-4b72ad755bca',
  toNative: [Function: toNative],
  sql: 'select * from "accounts"' }
> // restarted postgre
undefined
> knex('accounts').then(() => console.log('query success')).catch(err => console.log('fale', err))
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> { method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '37e6f236-c690-42e0-ae42-02240edb4d78',
  toNative: [Function: toNative],
  sql: 'select * from "accounts"' }
query success
> knex.transaction(trx => trx('accounts')).then(() => console.log('query success')).catch(err => console.log('fale', err))
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> { method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '8f885135-ca39-4079-9e2a-f6d82704b568',
  toNative: [Function: toNative],
  sql: 'select * from "accounts"' }
query success

> 
```

**Comment by analytik** [comment]
Hi @elhigu, thank you for putting effort into this! One more idea - since I'm using docker, the restarted postgres instance can have a different IP address than the previous one. Maybe you know - is the IP address of the service cached at any point, in the pool or in pg driver itself? If yes, that could be an easy thing to fix. 

If not, I will try to prepare some more extensive test and try to crawl the source code for clues. Thank you either way!

**Comment by elhigu** [comment]
@analytik I have no idea if pg caches resolved DNS address, maybe opening new issue would be good if you start figuring that out / allowing knex to re-resolve it after connection failures.

**Comment by cloutiertyler** [comment]
@elhigu I'm having very similar problems using knex `14.4` in docker, however, I don't even need to bring postgres down to reproduce it. I get the error simply by waiting a few minutes in between queries. Then it seems as though I have to burn through the pool of old connections before I stop getting the error. Specifically I get:

```Knex:warning - Connection Error: Connection ended unexpectedly```

and the connection hangs.

**Comment by cloutiertyler** [comment]
I rolled back to knex `12.6` and I'm having no problems at all there.

**Comment by elhigu** [comment]
@cloutiertyler There is no way to tell what is your problem in this case.

Would need some test code to reproduce the problem for example some docker-compose file etc. Please open new issue if you are able to provide code for reproducing the behaviour you are experiencing.

**Comment by necevil** [comment]
I think I am running into some variety of this issue with the Knex client that is used by Ghost blog (LTS 0.11.8) when connecting to a MySQL database outside of the Kibernetes cluster that is running ghost etc.

My issue sounds A LOT like the behavior that @cloutiertyler mentions.  I will work on creating a docker-compose stack to reproduce and will set the Knex debug flag to get some more information.  Posting this here primarily to tie others with the ghost Kibernetes use case to the possible problem since it took me a long time to find my way here!

**Comment by necevil** [comment]
@elhigu @cloutiertyler As mentioned above I am running on Azure AKS (Azure Kubernetes Service) and utilizing Ghost LTS (now 0.11.13 latest) which has a Knex dependency (by default Ghost LTS 0.11.13 depends on Knex 12.9).

I can't replicate the issue locally either but in production the client -> database connection is some how interrupted.  

My GUESS is that this happens at the same time that the Azure Kubernetes Browser UI disconnects / times out.  For AKS users who find this in the future you can run the browse ui with:
`az aks browse --resource-group <resource-group> --name <cluster-name>`

Essentially after 5 minutes or so of Idle it looks to me like all connections pointing out of the Cluster are closed.  That in theory would include both the connection to local UI Browse proxy  (mentioned above) which gives something like the following read out in console: 
E0605 13:29:52.670555    5586 portforward.go:178] lost connection to pod

My hypothesis is that this is also the same time that the Knex connection to my MySQL backend is severed, which then triggers the behavior discussed above.

The 'solution' that initially let me keep my production environment running was to set the MySQL server to terminate connections SOONER than the client connection is severed.  Since my Ghost Service is trying to continue using the connection (and expects it to stay open) this is not an issue of closing it when I am done (since I am not).  

So even though the Knex client thinks the connection should still be open, having the server CLOSE it on that side before it is severed by the container network timeout kept me from showing Error 503 to customers while I sorted the whole thing out.

The REAL solution is credit to @cloutiertyler which is rolling back to Knex 12.6
At that point for whatever reason the re-connection worked again as always though I have yet to remove the connection purging from my MySQL server so I am unsure if this plays a role.

This is a pretty specific use case but who knows, someone may find the Server Side pre-timeout disconnection hack useful.  Good luck guys!

**Comment by jazoom** [comment]
So the solution to this is roll back 3 major releases to Knex version `12.6`? That's a little uncomfortable.

**Comment by kibertoad** [comment]
@jazoom Have you tried latest 0.16.next version? I wonder if it's any better in this regard. If you can still reproduce the issue on a latest version, PR with failing test would be most appreciated

**Comment by kibertoad** [comment]
If test can't be created, then at least some kind of reproduction is essential for this to be fixed - e. g. docker-compose configuration file with manual steps to reproduce.

**Comment by jazoom** [comment]
That'll be tricky since it only happens once or twice per day in the production system. I think it might be related to idle time (as others here have also suggested). I've fiddled with the pool settings to see if that helps. It's 9pm now so I'll see how it goes overnight. The version is 15.x, I'm pretty sure.

**Comment by jazoom** [comment]
I guess I mean 0.15.x.

**Comment by jazoom** [comment]
Yes. Nothing is more frustrating than dealing with issues you can't reproduce.

I'll let you know how it goes. I'll also try updating to 0.16.x, but then I'll have to leave it for another day or two again.

By the way, this is in a Kubernetes cluster using Docker images. But, since pretty much everyone is using Docker nowadays I'm not sure if it's significant despite it being a commonality in this issue.

**Comment by kibertoad** [comment]
@jazoom It's more likely related to how database connections are managed server-side. Are you using some sort of cloud provider?

**Comment by jazoom** [comment]
No. I administer the cluster myself. I have other projects in the cluster, using Knex, connecting to the same database, that don't have this issue. One difference between the projects is this new one doesn't get nearly as much traffic and has little ongoing database activity.

**Comment by jazoom** [comment]
No errors overnight. I'll leave it for another day and see how it goes. If it seems to be fixed I'll share the changes I made.

**Comment by kibertoad** [comment]
@jazoom Thank you for the update!

**Comment by ChieveiT** [comment]
Has any one noticed that the pool used by knex(>=14.0) is actually [tarn](https://github.com/Vincit/tarn.js) rather than [generic-pool](https://github.com/coopernurse/node-pool) used by knex(<14.0) and mentioned in the document? If this issue is related to connection, I think the difference between tarn and generic-pool is the key.

I found my knex hang infinitely in production too. But I haven't reproduce it successfully in development yet. I turn on the internal debug option `DEBUG=knex:*`, try to both down mysql and disconnect network(when connect to a remote instance) but everything works fine. It looks tough. I am still working on it :(

**Comment by ChieveiT** [comment]
Has any one noticed that the pool used by knex(>=14.0) is actually [tarn](https://github.com/Vincit/tarn.js) rather than [generic-pool](https://github.com/coopernurse/node-pool) used by knex(<14.0) and mentioned in the document? If this issue is related to connection, I think the difference between tarn and generic-pool is the key.

I found my knex hang infinitely in production too. But I haven't reproduce it successfully in development yet. I turn on the internal debug option `DEBUG=knex:*`, try to both down mysql and disconnect network(when connect to a remote instance) but everything works fine. It looks tough. I am still working on it :(

**Comment by kibertoad** [comment]
@jazoom Thank you! I'll create a recipe out of this, do you remember what kind of error you were getting?

**Comment by jazoom** [comment]
>Has any one noticed that the pool used by knex(>=0.14.0) is actually tarn

Far out. Those docs really need to be updated. So it seems the `evictionRunIntervalMillis` option I used doesn't even exist then...

**Comment by jazoom** [comment]
@kibertoad `Connection Error: Connection ended unexpectedly`

**Comment by jazoom** [comment]
GitHub failing again

**Comment by kibertoad** [comment]
@jazoom I think I've updated the docs re: pool already, we just need to rebuild them after next version is out. Sorry for misleading info before that.

And thanks for the error message!

**Comment by elhigu** [comment]
@jazoom are you using mysql or mysql2 dialect? In my stress test I have noticed that some connection error is not caught correctly with mysql2 driver.

**Comment by elhigu** [comment]
@jazoom ah right ’pg’ then. And are you sure that connection is already broken when it is got from pool and doesnt get ended during a query being processed?

**Comment by jazoom** [comment]
@elhigu I'm not sure about anything here because I cannot reproduce this and it only happens once every few days in production. I also haven't had time to dig deep into it, which I know will take ages due to the nature of the problem.

**Comment by kibertoad** [comment]
@jazoom isn't "reapIntervalMillis" a tarn.js equivalent for "evictionRunIntervalMillis"?

**Comment by kibertoad** [comment]
Default is 1000 though, which should be fine,

**Comment by smulesoft** [comment]
@jazoom You should check [tarn](https://www.npmjs.com/package/tarn#usage) if you're using knex above version `0.14.0`. You can see [here](https://github.com/tgriesser/knex/compare/0.14.0...master) that #2450 was merged in that version.

**Comment by jazoom** [comment]
Yes I am very well aware now that Knex uses tarn. I knew as soon as @ChieveiT pointed it out.

I'm not convinced it's related to this issue, but others did have theirs fixed by downgrading, so that's interesting. I still haven't seen the issue again since I last reported it happened. I'm not even 100% convinced it's Knex's fault.

**Comment by smulesoft** [comment]
When I was testing this because we had the same problem in prod. In my case, I came up with an integration test that could reproduce the problem:
```
1. Do a batch of queries, they all work fine.
2. Shut down the database programatically.
3. Start the database again.
4. Do a batch of queries, see what happens.
```
I did steps `2` and `3` using `dockerode` to create/stop a postgres-docker-container in #2017.
It would be awesome if you do the same because you'll find a way to reproduce the issue, and to add it to knex test-suite to make sure it doesn't happen again in the future.

**Comment by kibertoad** [comment]
@smulesoft Would you consider contributing a test script that would be doing that?

**Comment by smulesoft** [comment]
Yeah, the PR I mentioned, #2017.

**Comment by elhigu** [comment]
Yeah, AFAIK that shouldn't be the problem anymore.

**Comment by kibertoad** [comment]
@elhigu Did #2017 land in one of 0.15.x releases or is it only in NEXT?

**Comment by elhigu** [comment]
@kibertoad I think it has been in already in 0.14 or something like that. Long enough that it was already broken at some point... I wouldn't have it implemented the way it was anymore and I haven't tried that recently.

**Comment by smulesoft** [comment]
@kibertoad Adding [this callback](https://github.com/tgriesser/knex/blob/c500d771ef9eda2f919d0bcd797bc75652d4c895/src/dialects/postgres/index.js#L117) was the fix to my problem. You can track it down to know in which release it was merged, but it was in 0.14 for sure.
Note that it was a fix for `PSQL`. I don't know who's having the problem now, but @jazoom mentioned CockroachDB, which may need to handle the problem in its own driver.

**Comment by kibertoad** [comment]
@smulesoft CockroachDB is actually using pg driver.

**Comment by smulesoft** [comment]
Thanks for the info. Then we should wait until we have a way to reproduce this consistently and then debug the problem...

**Comment by elhigu** [comment]
I think this issue has too much clutter already from ancient history and different issues, that this should be closed and add new issues when something reproducible happens. Closing.

**Comment by jazoom** [comment]
As a bit of closure, yesterday I finally worked out what the problem was in my case. It was actually a problem with the database, which has now been resolved with the latest version of CockroachDB that was just released.

**Comment by kibertoad** [comment]
@jazoom Glad to hear that! Would you consider providing a bit more details (e. g. link to resolved issue in CockroachDB tracker) for people with same issue who stumble upon this ticket?

**Comment by jazoom** [comment]
I actually don't know which issue it was fixed in, or even if it had an issue. I noticed sometimes the metrics would catch a spike in RAM and CPU usage and the CockroachDB logs said something about a heartbeat timeout.

I updated to version 2.1.0 (a major update with a great many fixes and changes) and the problem hasn't happened since. But, it's only been 1 day, so I can't be too sure.

**Comment by kibertoad** [comment]
@jazoom I would appreciate it if you reported back after having it run for a while, whether or not problem reappeared again :)

**Comment by jazoom** [comment]
No probs. Will do.

**Comment by jazoom** [comment]
It's been 3 days now and I still haven't seen the problem. Hopefully that means it has been resolved, at least in my case.

**Comment by kibertoad** [comment]
@jazoom Given that it was a week by now, is it still going strong?

**Comment by jazoom** [comment]
Actually, it happened once, but I'm pretty sure it was CockroachDB's fault, or perhaps a brief network outage. I don't think it had anything to do with Knex.

**Comment by necevil** [comment]
Hey guys,
Not sure if this one has been officially solved in the most recent versions or not — but on Azure AKS — when you are running Ghost with a remote database outside the cluster it was happening due to the Azure enforced 4 minute connection kill when connected to an external IP / port.

You can see some of my trouble shooting process over here:
[https://stackoverflow.com/questions/50706483/what-azure-kubernetes-aks-time-out-happens-to-disconnect-connections-in-out](https://stackoverflow.com/questions/50706483/what-azure-kubernetes-aks-time-out-happens-to-disconnect-connections-in-out)

Generally I was able to solve this previously (in the last iteration of my modified Ghost docker image) by rebuilding / rolling back to Knex 0.12.6.  Since Ghost uses MySql (by default) but some of my services on the cluster also need to connect to Postgres (Rails in this case) — as an added solution / redundancy I added a PGbouncer instance in order to separate any services connecting to external DBs from the connection pooling issue by enforcing a  DB connection drop on the PGbouncer instance (prior to Azure's 4 minute Load Balancer automatic connection severing).

If you are using Postgres and not MySQL you can solve the problem by adding PGBouncer in the middle and telling it to cycle connections frequently.

I don't know if the issue is still occurring but I am open to testing it with the latest version used by the official Ghost repo (Knex 0.14.6) if you guys have a test procedure!

**Comment by elhigu** [comment]
@brandonros if it is idle, then connections may be closed by the server or by pool and when new query is done, new connection is fetched to the pool if necessary... So no need to keepalive... you should never get  `Connection terminated unexpectedly` error when you are executing query, unless connection is terminated, after connection has been fetched out from pool (app has made query and connection terminated during it).

**Comment by jamesdixon** [comment]
@brandonros did you ever solve the issue?

**Comment by suryacaprice** [comment]
facing the same issue

**Comment by mremick** [comment]
@brandonros what was your solution?
